#!/bin/bash

# Update package lists
apt-get update

# Ensure Git and Apache2 are installed
puppet resource package git ensure=present
puppet resource package apache2 ensure=present

# Ensure Apache2 service is running
puppet resource service apache2 ensure=running

# Remove and recreate research directory
puppet resource file /tmp/2232220q/research ensure=absent force=true
puppet resource file /tmp/2232220q/research ensure=directory

# Clone the repository
puppet resource exec "git clone https://github.com/AmeerMus/2232220q_op_repo.git /tmp/2232220q/research" \
  command="/usr/bin/git clone https://github.com/AmeerMus/2232220q_op_repo.git /tmp/2232220q/research" \
  creates="/tmp/2232220q/research"

# Copy index.html to Apache web root
puppet resource file /var/www/html/index.html ensure=file source="/tmp/2232220q/research/2232220q_index.html" force=true
